---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monu
  namespace: devops
spec:
  replicas: 4
  selector:
    matchLabels:
      app: minnu
  template:
    metadata:
      labels:
        app: minnu
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: svc-4
spec:
  selector:
    app: minnu
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80

