apiVersion: v1
kind: Pod
metadata:
  name: dev
spec:
  containers:
  - name: cont-1
    image: nginx
    env:
    - name: value1
      valueFrom:
        configMapKeyRef:
          name: firstcm
          key: Place
    - name: value2
      valueFrom:
        configMapKeyRef:
          name: secondcm
          key: Company
