---
apiVersion: v1
kind: Pod
metadata:
  name: firstcm2
spec:
  containers:
    - name: cont-1
      image: httpd
      envFrom:
        - configMapRef:
            name: firstcm

        - configMapRef:
            name: secondcm

