apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: cont-1
    image: ubuntu
    command: ["/bin/bash", "-c", "touch /tmp/teja; sleep 300"]
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/teja/
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 30
