---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sonu
  namespace: devops
spec:
  replicas: 4
  selector:
    app: kinnu
  template:
    metadata:
      labels:
        app: kinnu
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: svc-2
spec:
  selector:
    app: kinnu
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

