apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devops
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
      - name: cont-1
        image: nginx
        ports:
        - containerPort: 80
