---
apiVersion: v1
kind: Pod
metadata:
  name: secondcm2
spec:
  containers:
    - name: cont-1
      image: nginx
      envFrom:
        - configMapRef:
            name: thirdcm

        - configMapRef:
            name: fourcm

