apiVersion: apps/v1
kind: Deployment
metadata:
  name: teja
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sonu
  template:
    metadata:
      labels:
        app: sonu
    spec:
      containers:
      - name: cont-1
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo hi everyone; sleep 5; done"]
        volumeMounts:
        - name: devops
          mountPath: "/tmp/jenkins"
      - name: cont-2
        image: centos
        command: ["/bin/bash", "-c", "while true; do echo hi everyone; sleep 5; done"]
        volumeMounts:
        - name: devops
          mountPath: "/opt/docker"
      volumes:
      - name: devops
        persistentVolumeClaim:
          claimName: pvc-1
