# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devo-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["*"]
    resources: ["services"]
    verbs: ["get", "list", "create"]
