# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: devo
rules:
  - apiGroups: ["*"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["*"]
    resources: ["services"]
    verbs: ["get", "list", "create", "delete"]
