# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: devo
rules:
  - apiGroups: ["*"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["*"]
    resources: ["services"]
    verbs: ["get", "list", "create", "delete"]

# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: devo
subjects:
  - kind: User
    name: mustafa
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io
